// This file was generated by RobotBuilder v0.0.2.
package org.usfirst.frc1884.RobotCode2013.subsystems;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc1884.RobotCode2013.RobotMap;
/**
 * This class controls the climber subsystem
 */
public class Climber extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid leftClimbingPiston = RobotMap.climberLeftClimbingPiston;
    DoubleSolenoid rightClimbingPiston = RobotMap.climberRightClimbingPiston;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
    public void extendClimber() {
        if(true) return; // @URGENT: remove
        leftClimbingPiston.set(DoubleSolenoid.Value.kForward); // @todo: check that these are the right direction (all four)
        rightClimbingPiston.set(DoubleSolenoid.Value.kForward);
    }
    
    public void retractClimber() {
        if(true) return; // @URGENT: remove
        leftClimbingPiston.set(DoubleSolenoid.Value.kReverse);
        rightClimbingPiston.set(DoubleSolenoid.Value.kReverse);
    }
}
