// This file was generated by RobotBuilder v0.0.2.
package org.usfirst.frc1884.RobotCode2013.subsystems;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc1884.RobotCode2013.RobotMap;
import org.usfirst.frc1884.RobotCode2013.commands.RetractFeederArm;
/**
 * This class controls the Feeder subsystem
 */
public class Feeder extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController feederIntake = RobotMap.feederFeederIntake;
    SpeedController feederArmMotor = RobotMap.feederFeederArmMotor;
    DigitalInput upperLimitSwitch = RobotMap.feederUpperLimitSwitch;
    DigitalInput lowerLimitSwitch = RobotMap.feederLowerLimitSwitch;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new RetractFeederArm());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
    public void setFeederIntakeSpeed(double value) {
        feederIntake.set(-value);
    }
    
    public void extendArm() {
        feederArmMotor.set(-0.4);
    }
    
    public void retractArm() {
        feederArmMotor.set(1.0);
    }
    
    public void armOff() {
        feederArmMotor.set(0.0);
    }
    
    public boolean getUpperSwitch() {
        return upperLimitSwitch.get();
    }
    
    public boolean getLowerSwitch() {
        return lowerLimitSwitch.get();
    }
}
