// This file was generated by RobotBuilder v0.0.2.
package org.usfirst.frc1884.RobotCode2013.subsystems;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc1884.RobotCode2013.RobotMap;
/**
 * This class controls the Feeder subsystem
 */
public class Feeder extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController feederIntake = RobotMap.feederFeederIntake;
    SpeedController feederArmMotor = RobotMap.feederFeederArmMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
    public void setFeederIntakeSpeed(double value) {
        feederIntake.set(-value);
    }
    
    public void extendArm() {
        feederArmMotor.set(-0.2);
        System.out.println("-0.2");
    }
    
    public void retractArm() {
        feederArmMotor.set(1.0);
        System.out.println("1.0");
    }
    
    public void armOff() {
        feederArmMotor.set(0.0);
        System.out.println("0.0");
    }
}
