// This file was generated by RobotBuilder v0.0.2.
package org.usfirst.frc1884.RobotCode2013.subsystems;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc1884.RobotCode2013.RobotMap;
import org.usfirst.frc1884.RobotCode2013.commands.SpinWheels;
/**
 * This class controls the shooter subsystem
 */
public class Shooter extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController firstWheel = RobotMap.shooterFirstWheel;
    SpeedController secondWheel = RobotMap.shooterSecondWheel;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new SpinWheels());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
    public void setShootingMotors(double firstWheelSpeed, double secondWheelSpeed) {
        firstWheel.set(firstWheelSpeed);
        secondWheel.set(secondWheelSpeed);
    }
}
